#!/usr/bin/env python3
"""Phase 2 v2: Restart all deploys using port computed from deployId hash.
Mirrors the JS getPortForDeploy function in deploy-executor.ts.
"""
import sys
sys.path.insert(0, '/home/z/.local/lib/python3.13/site-packages')
import paramiko, time, base64

VPS_HOST = '209.145.62.238'
VPS_USER = 'root'
VPS_PASS = 'LipeHost@2026'
PROJECT_DIR = '/var/www/lipehost'

def get_port_for_deploy(deploy_id: str) -> int:
    """Port of JS: hash = ((hash << 5) - hash) + charCode; 3001 + (abs(hash) % 999)"""
    h = 0
    for ch in deploy_id:
        h = ((h << 5) - h) + ord(ch)
        # Simulate JS 32-bit signed integer overflow
        h &= 0xFFFFFFFF
        if h >= 0x80000000:
            h -= 0x100000000
    return 3001 + (abs(h) % 999)


def run(ssh, cmd, timeout=120):
    print(f'  $ {cmd[:150]}')
    stdin, stdout, stderr = ssh.exec_command(cmd, timeout=timeout)
    out = stdout.read().decode('utf-8', errors='replace')
    err = stderr.read().decode('utf-8', errors='replace')
    exit_code = stdout.channel.exit_status
    if out.strip():
        for line in out.rstrip().split('\n')[:8]:
            print(f'    {line}')
    if err.strip():
        for line in err.rstrip().split('\n')[:3]:
            print(f'    ERR: {line}')
    return exit_code, out


def restart_deploy(ssh, deploy_id, name):
    deploy_dir = f"{PROJECT_DIR}/deploys/{deploy_id}"
    port = get_port_for_deploy(deploy_id)
    print(f'\n=== Restarting deploy: {name} ({deploy_id}) — port {port} ===')

    # Check if deploy dir exists
    ec, dir_check = run(ssh, f"test -d {deploy_dir} && echo EXISTS || echo MISSING", timeout=10)
    if 'MISSING' in dir_check:
        print(f'  ⚠️ Deploy dir does not exist — skipping')
        return

    # Find standalone directory: try standard path first
    ec, check_out = run(ssh, f"test -f {deploy_dir}/.next/standalone/server.js && echo 'STD' || echo 'NO_STD'", timeout=10)
    standalone_check = check_out.strip().split('\n')[-1].strip() if check_out else ''
    print(f'  Standalone at .next/standalone/server.js: {standalone_check}')

    standalone_dir = ''
    start_cmd = ''

    if standalone_check == 'STD':
        standalone_dir = f"{deploy_dir}/.next/standalone"
        start_cmd = f"PORT={port} NODE_ENV=production node server.js"
        print(f'  → Using standalone mode')
    else:
        # Try nested path — find server.js anywhere under .next
        ec, find_out = run(ssh, f"find {deploy_dir}/.next -name server.js -not -path '*/node_modules/*' -type f 2>/dev/null | head -1", timeout=15)
        found = (find_out or '').strip().split('\n')[-1].strip() if find_out else ''
        if found:
            standalone_dir = found.replace('/server.js', '')
            start_cmd = f"PORT={port} NODE_ENV=production node server.js"
            print(f'  → Found nested standalone: {standalone_dir}')
        else:
            # Fallback: npx next start
            standalone_dir = deploy_dir
            start_cmd = f"PORT={port} NODE_ENV=production npx next start -p {port}"
            print(f'  → No standalone found — using fallback: npx next start')

    # Create start.sh wrapper script
    db_path = f"{deploy_dir}/db/custom.db"
    start_script = f"""#!/bin/bash
# Auto-generated by LIPE.HOST deploy executor (phase2 restart)
cd {standalone_dir}
export PORT={port}
export NODE_ENV=production
export DATABASE_URL=file:{db_path}
export HOSTNAME=0.0.0.0
exec {start_cmd}
"""
    script_b64 = base64.b64encode(start_script.encode()).decode()
    run(ssh, f"echo '{script_b64}' | base64 -d > {deploy_dir}/start.sh && chmod 755 {deploy_dir}/start.sh && echo '  start.sh created'", timeout=15)

    # Ensure static files are copied if standalone
    if standalone_dir != deploy_dir:
        run(ssh, f"mkdir -p {standalone_dir}/public {standalone_dir}/.next/static 2>/dev/null; cp -rf {deploy_dir}/public/. {standalone_dir}/public/ 2>/dev/null; cp -rf {deploy_dir}/.next/static/. {standalone_dir}/.next/static/ 2>/dev/null; true", timeout=30)

    # Kill anything on the port
    run(ssh, f"fuser -k {port}/tcp 2>/dev/null; true", timeout=10)

    # Delete old PM2 processes (try both naming conventions)
    pm2_name_new = f"deploy-{deploy_id[:12]}"
    run(ssh, f"pm2 delete {pm2_name_new} 2>/dev/null; true", timeout=15)

    # Start with PM2 using the wrapper script
    run(ssh, f"pm2 start {deploy_dir}/start.sh --name {pm2_name_new} --cwd {standalone_dir} 2>&1", timeout=30)
    run(ssh, "pm2 save --force 2>&1 | tail -1", timeout=15)

    # Wait and check
    time.sleep(3)
    ec, http_out = run(ssh, f"curl -sS -o /dev/null -w 'HTTP %{{http_code}}' http://localhost:{port}/ 2>&1", timeout=15)
    print(f'  → Result: {http_out.strip().split(chr(10))[-1]}')


def main():
    print(f'Connecting to {VPS_HOST}...')
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(VPS_HOST, username=VPS_USER, password=VPS_PASS, timeout=15)
    print('✓ Connected')

    # Get all deploys from DB
    print('\n=== Listing deploys from DB ===')
    ec, db_out = run(ssh, f"cd {PROJECT_DIR} && sqlite3 db/custom.db \"SELECT id, name, status FROM Deploy ORDER BY createdAt DESC;\" 2>&1", timeout=15)
    print(f'\n{db_out}')

    # Parse deploy IDs
    deploys = []
    for line in db_out.strip().split('\n'):
        if '|' in line:
            parts = line.split('|')
            if len(parts) >= 2:
                deploy_id = parts[0].strip()
                name = parts[1].strip()
                status = parts[2].strip() if len(parts) > 2 else ''
                if deploy_id and not deploy_id.startswith('Error'):
                    deploys.append((deploy_id, name, status))

    print(f'\nFound {len(deploys)} deploys in DB')

    # Restart each deploy
    for deploy_id, name, status in deploys:
        try:
            restart_deploy(ssh, deploy_id, name)
        except Exception as e:
            print(f'  ❌ Error restarting {deploy_id}: {e}')

    # Final summary
    print('\n=== Final PM2 list ===')
    run(ssh, "pm2 list 2>&1", timeout=30)

    # Also check the existing abelha-deploy and energetico-deploy names — these are old PM2 entries
    # We should clean them up if they're duplicates of DB deploys
    print('\n=== Cleanup: deleting stale PM2 entries (abelha-deploy, energetico-deploy) ===')
    run(ssh, "pm2 delete abelha-deploy 2>/dev/null; pm2 delete energetico-deploy 2>/dev/null; pm2 save --force 2>&1 | tail -1", timeout=30)

    print('\n=== Final PM2 list after cleanup ===')
    run(ssh, "pm2 list 2>&1", timeout=30)

    ssh.close()
    print('\n🎉 PHASE 2 DONE — all deploys restarted with new wrapper approach!')


if __name__ == '__main__':
    main()
