#!/usr/bin/env python3
"""Phase 2: Restart all existing deploys with new wrapper script approach.
For each deploy:
  1. Find standalone (try .next/standalone/server.js, then find anywhere in .next)
  2. If found → start.sh with `node server.js` in standalone dir
  3. If not found → start.sh with `npx next start` in deploy dir
  4. Restart PM2 with the wrapper script
"""
import sys
sys.path.insert(0, '/home/z/.local/lib/python3.13/site-packages')
import paramiko, time, base64

VPS_HOST = '209.145.62.238'
VPS_USER = 'root'
VPS_PASS = 'LipeHost@2026'
PROJECT_DIR = '/var/www/lipehost'

def run(ssh, cmd, timeout=120):
    print(f'  $ {cmd[:150]}')
    stdin, stdout, stderr = ssh.exec_command(cmd, timeout=timeout)
    out = stdout.read().decode('utf-8', errors='replace')
    err = stderr.read().decode('utf-8', errors='replace')
    exit_code = stdout.channel.exit_status
    if out.strip():
        for line in out.rstrip().split('\n')[:8]:
            print(f'    {line}')
    if err.strip():
        for line in err.rstrip().split('\n')[:3]:
            print(f'    ERR: {line}')
    return exit_code, out


def restart_deploy(ssh, deploy_id):
    deploy_dir = f"{PROJECT_DIR}/deploys/{deploy_id}"
    print(f'\n=== Restarting deploy: {deploy_id} ===')

    # Get the port from the DB
    ec, port_out = run(ssh, f"cd {PROJECT_DIR} && sqlite3 db/custom.db \"SELECT port FROM Deploy WHERE id='{deploy_id}';\" 2>&1", timeout=15)
    port = port_out.strip().split('\n')[-1].strip() if port_out else ''
    if not port or not port.isdigit():
        print(f'  ⚠️ No port found for {deploy_id}, skipping')
        return
    print(f'  Port: {port}')

    # Find standalone directory: try standard path first
    ec, check_out = run(ssh, f"test -f {deploy_dir}/.next/standalone/server.js && echo 'STD' || echo 'NO_STD'", timeout=10)
    standalone_check = check_out.strip().split('\n')[-1].strip() if check_out else ''
    print(f'  Standalone check: {standalone_check}')

    standalone_dir = ''
    start_cmd = ''

    if standalone_check == 'STD':
        standalone_dir = f"{deploy_dir}/.next/standalone"
        start_cmd = f"PORT={port} NODE_ENV=production node server.js"
    else:
        # Try nested path
        ec, find_out = run(ssh, f"find {deploy_dir}/.next -name server.js -not -path '*/node_modules/*' -type f 2>/dev/null | head -1", timeout=15)
        found = find_out.strip().split('\n')[-1].strip() if find_out else ''
        if found:
            standalone_dir = found.replace('/server.js', '')
            start_cmd = f"PORT={port} NODE_ENV=production node server.js"
            print(f'  Found nested: {standalone_dir}')
        else:
            # Fallback: npx next start
            standalone_dir = deploy_dir
            start_cmd = f"PORT={port} NODE_ENV=production npx next start -p {port}"
            print(f'  No standalone found — using fallback: npx next start')

    print(f'  standaloneDir: {standalone_dir}')
    print(f'  startCmd: {start_cmd}')

    # Create start.sh wrapper script
    db_path = f"{deploy_dir}/db/custom.db"
    start_script = f"""#!/bin/bash
# Auto-generated by LIPE.HOST deploy executor (phase2 restart)
cd {standalone_dir}
export PORT={port}
export NODE_ENV=production
export DATABASE_URL=file:{db_path}
export HOSTNAME=0.0.0.0
exec {start_cmd}
"""
    script_b64 = base64.b64encode(start_script.encode()).decode()
    run(ssh, f"echo '{script_b64}' | base64 -d > {deploy_dir}/start.sh && chmod 755 {deploy_dir}/start.sh", timeout=15)

    # Ensure static files are copied if standalone
    if standalone_dir != deploy_dir:
        run(ssh, f"mkdir -p {standalone_dir}/public {standalone_dir}/.next/static && cp -rf {deploy_dir}/public/. {standalone_dir}/public/ 2>/dev/null || true && cp -rf {deploy_dir}/.next/static/. {standalone_dir}/.next/static/ 2>/dev/null || true", timeout=30)

    # Kill anything on the port
    run(ssh, f"fuser -k {port}/tcp 2>/dev/null || true", timeout=10)

    # Delete old PM2 process
    pm2_name = f"deploy-{deploy_id[:12]}"
    run(ssh, f"pm2 delete {pm2_name} 2>/dev/null || true", timeout=15)

    # Start with PM2 using the wrapper script
    run(ssh, f"pm2 start {deploy_dir}/start.sh --name {pm2_name} --cwd {standalone_dir} 2>&1", timeout=30)
    run(ssh, "pm2 save --force 2>&1 | tail -1", timeout=15)

    # Wait and check
    time.sleep(3)
    run(ssh, f"curl -sS -o /dev/null -w 'HTTP %{{http_code}}' http://localhost:{port}/ 2>&1", timeout=15)


def main():
    print(f'Connecting to {VPS_HOST}...')
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(VPS_HOST, username=VPS_USER, password=VPS_PASS, timeout=15)
    print('✓ Connected')

    # Get all deploys from the DB
    print('\n=== Listing deploys from DB ===')
    ec, db_out = run(ssh, f"cd {PROJECT_DIR} && sqlite3 db/custom.db \"SELECT id, name, status, port FROM Deploy ORDER BY createdAt DESC;\" 2>&1", timeout=15)
    print(f'\n{db_out}')

    # Parse deploy IDs
    deploy_ids = []
    for line in db_out.strip().split('\n'):
        if '|' in line:
            deploy_id = line.split('|')[0].strip()
            if deploy_id and not deploy_id.startswith('Error'):
                deploy_ids.append(deploy_id)

    print(f'\nFound {len(deploy_ids)} deploys: {deploy_ids}')

    # Restart each deploy
    for deploy_id in deploy_ids:
        try:
            restart_deploy(ssh, deploy_id)
        except Exception as e:
            print(f'  ❌ Error restarting {deploy_id}: {e}')

    # Final summary
    print('\n=== Final PM2 list ===')
    run(ssh, "pm2 list 2>&1", timeout=30)

    ssh.close()
    print('\n🎉 PHASE 2 DONE — all deploys restarted with new wrapper approach!')


if __name__ == '__main__':
    main()
