#!/usr/bin/env python3
"""Phase 3: Upload fixed deploy-executor.ts, restart all deploys with proper
start.sh (no env vars in startCmd), wait for ports to be free before starting.
"""
import sys
sys.path.insert(0, '/home/z/.local/lib/python3.13/site-packages')
import paramiko, time, base64

VPS_HOST = '209.145.62.238'
VPS_USER = 'root'
VPS_PASS = 'LipeHost@2026'
PROJECT_DIR = '/var/www/lipehost'


def get_port_for_deploy(deploy_id: str) -> int:
    """Port of JS: hash = ((hash << 5) - hash) + charCode; 3001 + (abs(hash) % 999)"""
    h = 0
    for ch in deploy_id:
        h = ((h << 5) - h) + ord(ch)
        h &= 0xFFFFFFFF
        if h >= 0x80000000:
            h -= 0x100000000
    return 3001 + (abs(h) % 999)


def run(ssh, cmd, timeout=120):
    print(f'  $ {cmd[:180]}')
    stdin, stdout, stderr = ssh.exec_command(cmd, timeout=timeout)
    out = stdout.read().decode('utf-8', errors='replace')
    err = stderr.read().decode('utf-8', errors='replace')
    exit_code = stdout.channel.exit_status
    if out.strip():
        for line in out.rstrip().split('\n')[:10]:
            print(f'    {line}')
    if err.strip():
        for line in err.rstrip().split('\n')[:3]:
            print(f'    ERR: {line}')
    return exit_code, out


def restart_deploy(ssh, deploy_id, name):
    deploy_dir = f"{PROJECT_DIR}/deploys/{deploy_id}"
    port = get_port_for_deploy(deploy_id)
    print(f'\n=== Restarting: {name} ({deploy_id}) — port {port} ===')

    # Check if deploy dir exists
    ec, dir_check = run(ssh, f"test -d {deploy_dir} && echo EXISTS || echo MISSING", timeout=10)
    if 'MISSING' in dir_check:
        print(f'  ⚠️ Deploy dir missing — marking as error in DB and skipping')
        run(ssh, f"cd {PROJECT_DIR} && sqlite3 db/custom.db \"UPDATE Deploy SET status='error', errorMessage='Deploy directory missing on disk' WHERE id='{deploy_id}';\"", timeout=15)
        return

    # Find standalone: try standard path first
    ec, check_out = run(ssh, f"test -f {deploy_dir}/.next/standalone/server.js && echo 'STD' || echo 'NO_STD'", timeout=10)
    standalone_check = check_out.strip().split('\n')[-1].strip() if check_out else ''

    standalone_dir = ''
    start_cmd = ''

    if standalone_check == 'STD':
        standalone_dir = f"{deploy_dir}/.next/standalone"
        start_cmd = "node server.js"
        print(f'  → Standard standalone mode')
    else:
        # Try nested path
        ec, find_out = run(ssh, f"find {deploy_dir}/.next -name server.js -not -path '*/node_modules/*' -type f 2>/dev/null | head -1", timeout=15)
        found = (find_out or '').strip().split('\n')[-1].strip() if find_out else ''
        if found:
            standalone_dir = found.replace('/server.js', '')
            start_cmd = "node server.js"
            print(f'  → Nested standalone: {standalone_dir}')
        else:
            # Fallback: npx next start
            standalone_dir = deploy_dir
            start_cmd = f"npx next start -p {port}"
            print(f'  → No standalone — fallback: npx next start')

    # Create start.sh wrapper — env vars are EXPORTED, then exec runs just the command
    db_path = f"{deploy_dir}/db/custom.db"
    start_script = f"""#!/bin/bash
# Auto-generated by LIPE.HOST deploy executor
cd {standalone_dir}
export PORT={port}
export NODE_ENV=production
export DATABASE_URL=file:{db_path}
export HOSTNAME=0.0.0.0
exec {start_cmd}
"""
    script_b64 = base64.b64encode(start_script.encode()).decode()
    run(ssh, f"echo '{script_b64}' | base64 -d > {deploy_dir}/start.sh && chmod 755 {deploy_dir}/start.sh", timeout=15)
    # Show the script for verification
    run(ssh, f"cat {deploy_dir}/start.sh", timeout=10)

    # Ensure static files are copied if standalone
    if standalone_dir != deploy_dir:
        run(ssh, f"mkdir -p {standalone_dir}/public {standalone_dir}/.next/static 2>/dev/null; cp -rf {deploy_dir}/public/. {standalone_dir}/public/ 2>/dev/null; cp -rf {deploy_dir}/.next/static/. {standalone_dir}/.next/static/ 2>/dev/null; true", timeout=30)

    pm2_name = f"deploy-{deploy_id[:12]}"

    # STEP 1: Stop & delete the PM2 process FIRST
    print(f'  → Stopping & deleting PM2 process {pm2_name}')
    run(ssh, f"pm2 stop {pm2_name} 2>/dev/null; pm2 delete {pm2_name} 2>/dev/null; true", timeout=15)

    # STEP 2: Kill anything listening on the port (wait for it to be free)
    print(f'  → Killing anything on port {port}')
    run(ssh, f"fuser -k {port}/tcp 2>/dev/null; true", timeout=10)
    time.sleep(2)  # Wait for OS to release the port
    # Verify port is free
    ec, port_check = run(ssh, f"curl -sS -o /dev/null -w '%{{http_code}}' --max-time 2 http://localhost:{port}/ 2>&1 || echo FREE", timeout=10)

    # STEP 3: Start with PM2 using the wrapper script
    print(f'  → Starting PM2 {pm2_name}')
    run(ssh, f"pm2 start {deploy_dir}/start.sh --name {pm2_name} --cwd {standalone_dir} 2>&1", timeout=30)
    run(ssh, "pm2 save --force 2>&1 | tail -1", timeout=15)

    # STEP 4: Wait for server to boot, then check
    time.sleep(5)
    ec, http_out = run(ssh, f"curl -sS -o /dev/null -w 'HTTP %{{http_code}}' --max-time 10 http://localhost:{port}/ 2>&1", timeout=20)
    http_status = http_out.strip().split('\n')[-1].strip()
    print(f'  → Result: {http_status}')

    # Update DB status
    if '200' in http_status or '30' in http_status or '40' in http_status:
        run(ssh, f"cd {PROJECT_DIR} && sqlite3 db/custom.db \"UPDATE Deploy SET status='ready', errorMessage=NULL WHERE id='{deploy_id}';\"", timeout=15)
        print(f'  ✓ Marked as ready in DB')
    else:
        run(ssh, f"cd {PROJECT_DIR} && sqlite3 db/custom.db \"UPDATE Deploy SET status='error', errorMessage='Server not responding on port {port}' WHERE id='{deploy_id}';\"", timeout=15)
        print(f'  ⚠️ Marked as error in DB')


def main():
    print(f'Connecting to {VPS_HOST}...')
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(VPS_HOST, username=VPS_USER, password=VPS_PASS, timeout=15)
    print('✓ Connected')

    # Upload the fixed deploy-executor.ts
    print('\n=== Uploading fixed deploy-executor.ts ===')
    sftp = ssh.open_sftp()
    sftp.put('/home/z/my-project/src/lib/deploy-executor.ts', f'{PROJECT_DIR}/src/lib/deploy-executor.ts')
    sftp.close()
    print('✓ Uploaded')

    # Verify the fix
    run(ssh, f"grep -c 'export PORT' {PROJECT_DIR}/src/lib/deploy-executor.ts")

    # Trigger rebuild in background — use setsid + disown so the SSH channel can close
    print('\n=== Triggering background rebuild ===')
    # Don't read stdout — just fire and forget
    ssh.exec_command(f"cd {PROJECT_DIR} && setsid bash -c 'NODE_ENV=production bun run build > /tmp/lipehost-build2.log 2>&1 && systemctl restart lipehost && echo DONE >> /tmp/lipehost-build2.log' </dev/null >/dev/null 2>&1 &", timeout=5)
    time.sleep(2)
    print('  → Build started in background')

    # Get all deploys from DB
    print('\n=== Listing deploys from DB ===')
    ec, db_out = run(ssh, f"cd {PROJECT_DIR} && sqlite3 db/custom.db \"SELECT id, name, status FROM Deploy ORDER BY createdAt DESC;\" 2>&1", timeout=15)

    # Parse deploy IDs
    deploys = []
    for line in db_out.strip().split('\n'):
        if '|' in line:
            parts = line.split('|')
            if len(parts) >= 2:
                deploy_id = parts[0].strip()
                name = parts[1].strip()
                if deploy_id and not deploy_id.startswith('Error'):
                    deploys.append((deploy_id, name))

    print(f'\nFound {len(deploys)} deploys in DB: {[(n, d[:8]) for d, n in deploys]}')

    # Restart each deploy (sequentially to avoid port conflicts)
    for deploy_id, name in deploys:
        try:
            restart_deploy(ssh, deploy_id, name)
        except Exception as e:
            print(f'  ❌ Error: {e}')

    # Final PM2 list
    print('\n=== Final PM2 list ===')
    run(ssh, "pm2 list 2>&1", timeout=30)

    # Final verification: curl each deploy
    print('\n=== Final verification ===')
    for deploy_id, name in deploys:
        port = get_port_for_deploy(deploy_id)
        run(ssh, f"curl -sS -o /dev/null -w '{name} (port {port}): HTTP %{{http_code}}\\n' --max-time 5 http://localhost:{port}/ 2>&1", timeout=15)

    ssh.close()
    print('\n🎉 PHASE 3 DONE!')


if __name__ == '__main__':
    main()
